title: Conservation Tech Lab
description: Developing open-source technology and machine learning tools for wildlife conservation and ecological research
baseurl: ""
url: "https://conservationtechlab.github.io"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor
